# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TELAINICIALGERENTE.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Tela_InicialGerente(object):
    """
    Classe responsavel por criar uma tela inicial 
    
    Essa classe ira gerar uma tela inicial que sera a primeira tela que o 
    usuario(administrador) vai ser direcionada, na qual tera a opcao de se
    cadastrar e logar no sistema
    
    
    """
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(13)
        MainWindow.setFont(font)
        MainWindow.setStyleSheet("background-color: rgb(255, 164, 70);")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(180, 20, 501, 41))
        font = QtGui.QFont()
        font.setFamily("MV Boli")
        font.setPointSize(20)
        font.setBold(False)
        font.setItalic(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet("font: 20pt \"MV Boli\";\n"
"")
        self.label.setObjectName("label")
        self.pushButton_2 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_2.setGeometry(QtCore.QRect(190, 80, 481, 51))
        self.pushButton_2.setStyleSheet("background-color: rgb(86, 105, 129);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_3 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_3.setGeometry(QtCore.QRect(190, 150, 481, 51))
        self.pushButton_3.setStyleSheet("background-color: rgb(86, 105, 129);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_4 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_4.setGeometry(QtCore.QRect(190, 290, 481, 51))
        self.pushButton_4.setStyleSheet("background-color: rgb(86, 105, 129);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_5 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_5.setGeometry(QtCore.QRect(190, 430, 481, 51))
        self.pushButton_5.setStyleSheet("background-color: rgb(86, 105, 129);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_6 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_6.setGeometry(QtCore.QRect(540, 490, 131, 41))
        self.pushButton_6.setStyleSheet("background-color: rgb(86, 105, 129);\n"
"background-color: rgb(255, 92, 51);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_7 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_7.setGeometry(QtCore.QRect(190, 490, 131, 41))
        self.pushButton_7.setStyleSheet("background-color: rgb(86, 105, 129);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_8.setGeometry(QtCore.QRect(190, 220, 481, 51))
        self.pushButton_8.setStyleSheet("background-color: rgb(86, 105, 129);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_9 = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_9.setGeometry(QtCore.QRect(190, 360, 481, 51))
        self.pushButton_9.setStyleSheet("background-color: rgb(86, 105, 129);\n"
"font: 10pt \"MS Shell Dlg 2\";\n"
"color: rgb(255, 255, 255);")
        self.pushButton_9.setObjectName("pushButton_9")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 26))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "BEM VINDO AO OASIS HOTEL"))
        self.pushButton_2.setText(_translate("MainWindow", "CADASTRAR USUÁRIO"))
        self.pushButton_3.setText(_translate("MainWindow", "CADASTRAR QUARTOS"))
        self.pushButton_4.setText(_translate("MainWindow", "VISUALIZAR RESERVAS"))
        self.pushButton_5.setText(_translate("MainWindow", "CANCELAR RESERVA"))
        self.pushButton_6.setText(_translate("MainWindow", "SAIR"))
        self.pushButton_7.setText(_translate("MainWindow", "VOLTAR"))
        self.pushButton_8.setText(_translate("MainWindow", "REALIZAR RESERVA"))
        self.pushButton_9.setText(_translate("MainWindow", "VISUALIZAR QUARTOS"))

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Tela_InicialGerente()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())